<?php

namespace ContainerHruPi7w;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XBoUSmhService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XBoUSmh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\AdminController::dashboard' => ['privates', '.service_locator.sVG_MVR.App\\Controller\\AdminController::dashboard()', 'getAdminControllerdashboardService', true],
            'App\\Controller\\AdminProjectController::create' => ['privates', '.service_locator.Z3W3Vct.App\\Controller\\AdminProjectController::create()', 'getAdminProjectControllercreateService', true],
            'App\\Controller\\AdminProjectController::edit' => ['privates', '.service_locator.fJjPRXR.App\\Controller\\AdminProjectController::edit()', 'getAdminProjectControllereditService', true],
            'App\\Controller\\AdminProjectController::delete' => ['privates', '.service_locator.jWDDN.5.App\\Controller\\AdminProjectController::delete()', 'getAdminProjectControllerdeleteService', true],
            'App\\Controller\\ContactController::process' => ['privates', '.service_locator._auvPC0.App\\Controller\\ContactController::process()', 'getContactControllerprocessService', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.lfM9NLF.App\\Controller\\HomeController::index()', 'getHomeControllerindexService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.0MQaTBY.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\AdminController:dashboard' => ['privates', '.service_locator.sVG_MVR.App\\Controller\\AdminController::dashboard()', 'getAdminControllerdashboardService', true],
            'App\\Controller\\AdminProjectController:create' => ['privates', '.service_locator.Z3W3Vct.App\\Controller\\AdminProjectController::create()', 'getAdminProjectControllercreateService', true],
            'App\\Controller\\AdminProjectController:edit' => ['privates', '.service_locator.fJjPRXR.App\\Controller\\AdminProjectController::edit()', 'getAdminProjectControllereditService', true],
            'App\\Controller\\AdminProjectController:delete' => ['privates', '.service_locator.jWDDN.5.App\\Controller\\AdminProjectController::delete()', 'getAdminProjectControllerdeleteService', true],
            'App\\Controller\\ContactController:process' => ['privates', '.service_locator._auvPC0.App\\Controller\\ContactController::process()', 'getContactControllerprocessService', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.lfM9NLF.App\\Controller\\HomeController::index()', 'getHomeControllerindexService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.0MQaTBY.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\AdminController::dashboard' => '?',
            'App\\Controller\\AdminProjectController::create' => '?',
            'App\\Controller\\AdminProjectController::edit' => '?',
            'App\\Controller\\AdminProjectController::delete' => '?',
            'App\\Controller\\ContactController::process' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\AdminController:dashboard' => '?',
            'App\\Controller\\AdminProjectController:create' => '?',
            'App\\Controller\\AdminProjectController:edit' => '?',
            'App\\Controller\\AdminProjectController:delete' => '?',
            'App\\Controller\\ContactController:process' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\SecurityController:login' => '?',
        ]);

        if (isset($container->privates['.service_locator.XBoUSmh'])) {
            return $container->privates['.service_locator.XBoUSmh'];
        }

        return $container->privates['.service_locator.XBoUSmh'] = $instance;
    }
}
