<?php

namespace ContainerHruPi7w;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get__Tailwind_Command_Update_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '..tailwind.command.update.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'LazyCommand.php';

        return $container->privates['..tailwind.command.update.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('tailwind:update', [], 'Updates the Tailwind CSS binary to the latest version within the current major', false, #[\Closure(name: '.tailwind.command.update', class: 'Symfonycasts\\TailwindBundle\\Command\\TailwindUpdateCommand')] fn (): \Symfonycasts\TailwindBundle\Command\TailwindUpdateCommand => ($container->privates['.tailwind.command.update'] ?? $container->load('get_Tailwind_Command_UpdateService')));
    }
}
