<?php

namespace ContainerHruPi7w;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminProjectControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jWDDN.5.App\Controller\AdminProjectController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jWDDN.5.App\\Controller\\AdminProjectController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'projectRepository' => ['privates', 'App\\Repository\\ProjectRepository', 'getProjectRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'projectRepository' => 'App\\Repository\\ProjectRepository',
            'em' => '?',
        ]))->withContext('App\\Controller\\AdminProjectController::delete()', $container);
    }
}
