<?php

namespace ContainerHruPi7w;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminProjectControllercreateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Z3W3Vct.App\Controller\AdminProjectController::create()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'validator' => ['privates', 'debug.validator', 'getDebug_ValidatorService', false],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'validator' => '?',
            'em' => '?',
        ]))->withContext('App\\Controller\\AdminProjectController::create()', $container);

        if (isset($container->privates['.service_locator.Z3W3Vct.App\\Controller\\AdminProjectController::create()'])) {
            return $container->privates['.service_locator.Z3W3Vct.App\\Controller\\AdminProjectController::create()'];
        }

        return $container->privates['.service_locator.Z3W3Vct.App\\Controller\\AdminProjectController::create()'] = $instance;
    }
}
