<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHruPi7w\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHruPi7w/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHruPi7w.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHruPi7w\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHruPi7w\App_KernelDevDebugContainer([
    'container.build_hash' => 'HruPi7w',
    'container.build_id' => 'fd1d11cb',
    'container.build_time' => 1787886391,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHruPi7w');
